
cache:
  paths:
    - node_modules/

deploy_stage:
  only:
    - master
  script:
    - rm ./package-lock.json
    - npm install
    - npm run build:prod
    - npm run test
    - ./node_modules/@angular/cli/bin/ng test --progress false --single-run=true --watch=false

