name: Build
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.17.0]

    steps:
      - uses: actions/checkout@v1

      - name: Node $
        uses: actions/setup-node@v1
        with:
          node-version: 10.17.0

      - name: npm install and npm run build
        run: |
          npm install
          npm install @angular/cli -g
          npm run build:ci 
